// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/23/2025, 10:28:58 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/cheikhmbackegaye/Documents/Projects/workion-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/plugins/**/*.{js,ts,mjs}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/composables/**/*.{js,ts,mjs}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/utils/**/*.{js,ts,mjs}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/app.config.{js,ts,mjs}","/Users/cheikhmbackegaye/Documents/Projects/workion-web/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;